### PR TITLE
Add 'Edit' functionality to each row

### PR DESCRIPTION
**Pull request by zbstof**

### CODE REVIEW

**Comment by zbstof** [comment]
Should fix #2

**Comment by PandelisZ** [comment]
Bump.

**Comment by pigsflew** [comment]
Bump--please merge?

**Comment by aspiers** [comment]
@bendavis78 Please could this be merged? Having edit functionality would be a big improvement! Thanks!

**Comment by filbo** [comment]
@bendavis78 Chiming in with the others: can you please update this extension with the provided PRs?  It's a nice small extension that does exactly what's needed, just wants a little polish.  Other choices in the Chrome extensions swamp look dodgy.

I can build it myself _for_ myself, but if I want to recommend it to friends, it needs to be a formally posted extension in a 'store'.  There is value in ongoing minor maintenance of a simple extension like this.

**Pull request merged**
